/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type InstanceMetadataEndpointState string

const (
	InstanceMetadataEndpointState_disabled InstanceMetadataEndpointState = "disabled"
	InstanceMetadataEndpointState_enabled  InstanceMetadataEndpointState = "enabled"
)

type InstanceMetadataHTTPTokensState string

const (
	InstanceMetadataHTTPTokensState_optional InstanceMetadataHTTPTokensState = "optional"
	InstanceMetadataHTTPTokensState_required InstanceMetadataHTTPTokensState = "required"
)

type InstanceRefreshStatus string

const (
	InstanceRefreshStatus_Pending    InstanceRefreshStatus = "Pending"
	InstanceRefreshStatus_InProgress InstanceRefreshStatus = "InProgress"
	InstanceRefreshStatus_Successful InstanceRefreshStatus = "Successful"
	InstanceRefreshStatus_Failed     InstanceRefreshStatus = "Failed"
	InstanceRefreshStatus_Cancelling InstanceRefreshStatus = "Cancelling"
	InstanceRefreshStatus_Cancelled  InstanceRefreshStatus = "Cancelled"
)

type LifecycleState string

const (
	LifecycleState_Pending             LifecycleState = "Pending"
	LifecycleState_Pending_Wait        LifecycleState = "Pending:Wait"
	LifecycleState_Pending_Proceed     LifecycleState = "Pending:Proceed"
	LifecycleState_Quarantined         LifecycleState = "Quarantined"
	LifecycleState_InService           LifecycleState = "InService"
	LifecycleState_Terminating         LifecycleState = "Terminating"
	LifecycleState_Terminating_Wait    LifecycleState = "Terminating:Wait"
	LifecycleState_Terminating_Proceed LifecycleState = "Terminating:Proceed"
	LifecycleState_Terminated          LifecycleState = "Terminated"
	LifecycleState_Detaching           LifecycleState = "Detaching"
	LifecycleState_Detached            LifecycleState = "Detached"
	LifecycleState_EnteringStandby     LifecycleState = "EnteringStandby"
	LifecycleState_Standby             LifecycleState = "Standby"
)

type MetricStatistic string

const (
	MetricStatistic_Average     MetricStatistic = "Average"
	MetricStatistic_Minimum     MetricStatistic = "Minimum"
	MetricStatistic_Maximum     MetricStatistic = "Maximum"
	MetricStatistic_SampleCount MetricStatistic = "SampleCount"
	MetricStatistic_Sum         MetricStatistic = "Sum"
)

type MetricType string

const (
	MetricType_ASGAverageCPUUtilization MetricType = "ASGAverageCPUUtilization"
	MetricType_ASGAverageNetworkIn      MetricType = "ASGAverageNetworkIn"
	MetricType_ASGAverageNetworkOut     MetricType = "ASGAverageNetworkOut"
	MetricType_ALBRequestCountPerTarget MetricType = "ALBRequestCountPerTarget"
)

type RefreshStrategy string

const (
	RefreshStrategy_Rolling RefreshStrategy = "Rolling"
)

type ScalingActivityStatusCode string

const (
	ScalingActivityStatusCode_PendingSpotBidPlacement         ScalingActivityStatusCode = "PendingSpotBidPlacement"
	ScalingActivityStatusCode_WaitingForSpotInstanceRequestId ScalingActivityStatusCode = "WaitingForSpotInstanceRequestId"
	ScalingActivityStatusCode_WaitingForSpotInstanceId        ScalingActivityStatusCode = "WaitingForSpotInstanceId"
	ScalingActivityStatusCode_WaitingForInstanceId            ScalingActivityStatusCode = "WaitingForInstanceId"
	ScalingActivityStatusCode_PreInService                    ScalingActivityStatusCode = "PreInService"
	ScalingActivityStatusCode_InProgress                      ScalingActivityStatusCode = "InProgress"
	ScalingActivityStatusCode_WaitingForELBConnectionDraining ScalingActivityStatusCode = "WaitingForELBConnectionDraining"
	ScalingActivityStatusCode_MidLifecycleAction              ScalingActivityStatusCode = "MidLifecycleAction"
	ScalingActivityStatusCode_WaitingForInstanceWarmup        ScalingActivityStatusCode = "WaitingForInstanceWarmup"
	ScalingActivityStatusCode_Successful                      ScalingActivityStatusCode = "Successful"
	ScalingActivityStatusCode_Failed                          ScalingActivityStatusCode = "Failed"
	ScalingActivityStatusCode_Cancelled                       ScalingActivityStatusCode = "Cancelled"
)
