/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
)

// +kubebuilder:skipversion
type Activity struct {
	ActivityID *string `json:"activityID,omitempty"`

	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	Cause *string `json:"cause,omitempty"`

	Description *string `json:"description,omitempty"`

	Details *string `json:"details,omitempty"`

	EndTime *metav1.Time `json:"endTime,omitempty"`

	StartTime *metav1.Time `json:"startTime,omitempty"`

	StatusMessage *string `json:"statusMessage,omitempty"`
}

// +kubebuilder:skipversion
type AdjustmentType struct {
	AdjustmentType *string `json:"adjustmentType,omitempty"`
}

// +kubebuilder:skipversion
type Alarm struct {
	AlarmARN *string `json:"alarmARN,omitempty"`

	AlarmName *string `json:"alarmName,omitempty"`
}

// +kubebuilder:skipversion
type BlockDeviceMapping struct {
	DeviceName *string `json:"deviceName,omitempty"`
	// Describes information used to set up an Amazon EBS volume specified in a
	// block device mapping.
	EBS *EBS `json:"ebs,omitempty"`

	NoDevice *bool `json:"noDevice,omitempty"`

	VirtualName *string `json:"virtualName,omitempty"`
}

// +kubebuilder:skipversion
type EBS struct {
	DeleteOnTermination *bool `json:"deleteOnTermination,omitempty"`

	Encrypted *bool `json:"encrypted,omitempty"`

	IOPS *int64 `json:"iops,omitempty"`

	SnapshotID *string `json:"snapshotID,omitempty"`

	VolumeSize *int64 `json:"volumeSize,omitempty"`

	VolumeType *string `json:"volumeType,omitempty"`
}

// +kubebuilder:skipversion
type EnabledMetric struct {
	Granularity *string `json:"granularity,omitempty"`

	Metric *string `json:"metric,omitempty"`
}

// +kubebuilder:skipversion
type FailedScheduledUpdateGroupActionRequest struct {
	ErrorCode *string `json:"errorCode,omitempty"`

	ErrorMessage *string `json:"errorMessage,omitempty"`

	ScheduledActionName *string `json:"scheduledActionName,omitempty"`
}

// +kubebuilder:skipversion
type Filter struct {
	Name *string `json:"name,omitempty"`
}

// +kubebuilder:skipversion
type Group struct {
	AutoScalingGroupARN *string `json:"autoScalingGroupARN,omitempty"`

	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	AvailabilityZones []*string `json:"availabilityZones,omitempty"`

	CapacityRebalance *bool `json:"capacityRebalance,omitempty"`

	CreatedTime *metav1.Time `json:"createdTime,omitempty"`

	DefaultCooldown *int64 `json:"defaultCooldown,omitempty"`

	DesiredCapacity *int64 `json:"desiredCapacity,omitempty"`

	EnabledMetrics []*EnabledMetric `json:"enabledMetrics,omitempty"`

	HealthCheckGracePeriod *int64 `json:"healthCheckGracePeriod,omitempty"`

	HealthCheckType *string `json:"healthCheckType,omitempty"`

	Instances []*Instance `json:"instances,omitempty"`

	LaunchConfigurationName *string `json:"launchConfigurationName,omitempty"`
	// Describes the Amazon EC2 launch template and the launch template version
	// that can be used by an Auto Scaling group to configure Amazon EC2 instances.
	//
	// The launch template that is specified must be configured for use with an
	// Auto Scaling group. For more information, see Creating a launch template
	// for an Auto Scaling group (https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html)
	// in the Amazon EC2 Auto Scaling User Guide.
	LaunchTemplate *LaunchTemplateSpecification `json:"launchTemplate,omitempty"`

	LoadBalancerNames []*string `json:"loadBalancerNames,omitempty"`

	MaxInstanceLifetime *int64 `json:"maxInstanceLifetime,omitempty"`

	MaxSize *int64 `json:"maxSize,omitempty"`

	MinSize *int64 `json:"minSize,omitempty"`
	// Describes a mixed instances policy for an Auto Scaling group. With mixed
	// instances, your Auto Scaling group can provision a combination of On-Demand
	// Instances and Spot Instances across multiple instance types. For more information,
	// see Auto Scaling groups with multiple instance types and purchase options
	// (https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html)
	// in the Amazon EC2 Auto Scaling User Guide.
	//
	// You can create a mixed instances policy for a new Auto Scaling group, or
	// you can create it for an existing group by updating the group to specify
	// MixedInstancesPolicy as the top-level parameter instead of a launch configuration
	// or launch template.
	MixedInstancesPolicy *MixedInstancesPolicy `json:"mixedInstancesPolicy,omitempty"`

	NewInstancesProtectedFromScaleIn *bool `json:"newInstancesProtectedFromScaleIn,omitempty"`

	PlacementGroup *string `json:"placementGroup,omitempty"`

	ServiceLinkedRoleARN *string `json:"serviceLinkedRoleARN,omitempty"`

	Status *string `json:"status,omitempty"`

	SuspendedProcesses []*SuspendedProcess `json:"suspendedProcesses,omitempty"`

	Tags []*TagDescription `json:"tags,omitempty"`

	TargetGroupARNs []*string `json:"targetGroupARNs,omitempty"`

	TerminationPolicies []*string `json:"terminationPolicies,omitempty"`

	VPCZoneIdentifier *string `json:"vpcZoneIdentifier,omitempty"`
}

// +kubebuilder:skipversion
type Instance struct {
	AvailabilityZone *string `json:"availabilityZone,omitempty"`

	HealthStatus *string `json:"healthStatus,omitempty"`

	InstanceID *string `json:"instanceID,omitempty"`

	InstanceType *string `json:"instanceType,omitempty"`

	LaunchConfigurationName *string `json:"launchConfigurationName,omitempty"`
	// Describes the Amazon EC2 launch template and the launch template version
	// that can be used by an Auto Scaling group to configure Amazon EC2 instances.
	//
	// The launch template that is specified must be configured for use with an
	// Auto Scaling group. For more information, see Creating a launch template
	// for an Auto Scaling group (https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html)
	// in the Amazon EC2 Auto Scaling User Guide.
	LaunchTemplate *LaunchTemplateSpecification `json:"launchTemplate,omitempty"`

	LifecycleState *string `json:"lifecycleState,omitempty"`

	ProtectedFromScaleIn *bool `json:"protectedFromScaleIn,omitempty"`

	WeightedCapacity *string `json:"weightedCapacity,omitempty"`
}

// +kubebuilder:skipversion
type InstanceDetails struct {
	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	AvailabilityZone *string `json:"availabilityZone,omitempty"`

	HealthStatus *string `json:"healthStatus,omitempty"`

	InstanceID *string `json:"instanceID,omitempty"`

	InstanceType *string `json:"instanceType,omitempty"`

	LaunchConfigurationName *string `json:"launchConfigurationName,omitempty"`
	// Describes the Amazon EC2 launch template and the launch template version
	// that can be used by an Auto Scaling group to configure Amazon EC2 instances.
	//
	// The launch template that is specified must be configured for use with an
	// Auto Scaling group. For more information, see Creating a launch template
	// for an Auto Scaling group (https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html)
	// in the Amazon EC2 Auto Scaling User Guide.
	LaunchTemplate *LaunchTemplateSpecification `json:"launchTemplate,omitempty"`

	LifecycleState *string `json:"lifecycleState,omitempty"`

	ProtectedFromScaleIn *bool `json:"protectedFromScaleIn,omitempty"`

	WeightedCapacity *string `json:"weightedCapacity,omitempty"`
}

// +kubebuilder:skipversion
type InstanceMetadataOptions struct {
	HTTPEndpoint *string `json:"httpEndpoint,omitempty"`

	HTTPPutResponseHopLimit *int64 `json:"httpPutResponseHopLimit,omitempty"`

	HTTPTokens *string `json:"httpTokens,omitempty"`
}

// +kubebuilder:skipversion
type InstanceMonitoring struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// +kubebuilder:skipversion
type InstanceRefresh struct {
	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	EndTime *metav1.Time `json:"endTime,omitempty"`

	InstanceRefreshID *string `json:"instanceRefreshID,omitempty"`

	StartTime *metav1.Time `json:"startTime,omitempty"`

	StatusReason *string `json:"statusReason,omitempty"`
}

// +kubebuilder:skipversion
type InstancesDistribution struct {
	OnDemandAllocationStrategy *string `json:"onDemandAllocationStrategy,omitempty"`

	OnDemandBaseCapacity *int64 `json:"onDemandBaseCapacity,omitempty"`

	OnDemandPercentageAboveBaseCapacity *int64 `json:"onDemandPercentageAboveBaseCapacity,omitempty"`

	SpotAllocationStrategy *string `json:"spotAllocationStrategy,omitempty"`

	SpotInstancePools *int64 `json:"spotInstancePools,omitempty"`

	SpotMaxPrice *string `json:"spotMaxPrice,omitempty"`
}

// +kubebuilder:skipversion
type LaunchConfiguration_SDK struct {
	AssociatePublicIPAddress *bool `json:"associatePublicIPAddress,omitempty"`

	BlockDeviceMappings []*BlockDeviceMapping `json:"blockDeviceMappings,omitempty"`

	ClassicLinkVPCID *string `json:"classicLinkVPCID,omitempty"`

	ClassicLinkVPCSecurityGroups []*string `json:"classicLinkVPCSecurityGroups,omitempty"`

	CreatedTime *metav1.Time `json:"createdTime,omitempty"`

	EBSOptimized *bool `json:"ebsOptimized,omitempty"`

	IAMInstanceProfile *string `json:"iamInstanceProfile,omitempty"`

	ImageID *string `json:"imageID,omitempty"`
	// Describes whether detailed monitoring is enabled for the Auto Scaling instances.
	InstanceMonitoring *InstanceMonitoring `json:"instanceMonitoring,omitempty"`

	InstanceType *string `json:"instanceType,omitempty"`

	KernelID *string `json:"kernelID,omitempty"`

	KeyName *string `json:"keyName,omitempty"`

	LaunchConfigurationARN *string `json:"launchConfigurationARN,omitempty"`

	LaunchConfigurationName *string `json:"launchConfigurationName,omitempty"`
	// The metadata options for the instances. For more information, see Configuring
	// the Instance Metadata Options (https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-config.html#launch-configurations-imds)
	// in the Amazon EC2 Auto Scaling User Guide.
	MetadataOptions *InstanceMetadataOptions `json:"metadataOptions,omitempty"`

	PlacementTenancy *string `json:"placementTenancy,omitempty"`

	RamdiskID *string `json:"ramdiskID,omitempty"`

	SecurityGroups []*string `json:"securityGroups,omitempty"`

	SpotPrice *string `json:"spotPrice,omitempty"`

	UserData *string `json:"userData,omitempty"`
}

// +kubebuilder:skipversion
type LaunchTemplate struct {
	// Describes the Amazon EC2 launch template and the launch template version
	// that can be used by an Auto Scaling group to configure Amazon EC2 instances.
	//
	// The launch template that is specified must be configured for use with an
	// Auto Scaling group. For more information, see Creating a launch template
	// for an Auto Scaling group (https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html)
	// in the Amazon EC2 Auto Scaling User Guide.
	LaunchTemplateSpecification *LaunchTemplateSpecification `json:"launchTemplateSpecification,omitempty"`

	Overrides []*LaunchTemplateOverrides `json:"overrides,omitempty"`
}

// +kubebuilder:skipversion
type LaunchTemplateOverrides struct {
	InstanceType *string `json:"instanceType,omitempty"`
	// Describes the Amazon EC2 launch template and the launch template version
	// that can be used by an Auto Scaling group to configure Amazon EC2 instances.
	//
	// The launch template that is specified must be configured for use with an
	// Auto Scaling group. For more information, see Creating a launch template
	// for an Auto Scaling group (https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html)
	// in the Amazon EC2 Auto Scaling User Guide.
	LaunchTemplateSpecification *LaunchTemplateSpecification `json:"launchTemplateSpecification,omitempty"`

	WeightedCapacity *string `json:"weightedCapacity,omitempty"`
}

// +kubebuilder:skipversion
type LaunchTemplateSpecification struct {
	LaunchTemplateID *string `json:"launchTemplateID,omitempty"`

	LaunchTemplateName *string `json:"launchTemplateName,omitempty"`

	Version *string `json:"version,omitempty"`
}

// +kubebuilder:skipversion
type LifecycleHook struct {
	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	DefaultResult *string `json:"defaultResult,omitempty"`

	HeartbeatTimeout *int64 `json:"heartbeatTimeout,omitempty"`

	LifecycleHookName *string `json:"lifecycleHookName,omitempty"`

	LifecycleTransition *string `json:"lifecycleTransition,omitempty"`

	NotificationMetadata *string `json:"notificationMetadata,omitempty"`

	NotificationTargetARN *string `json:"notificationTargetARN,omitempty"`

	RoleARN *string `json:"roleARN,omitempty"`
}

// +kubebuilder:skipversion
type LifecycleHookSpecification struct {
	DefaultResult *string `json:"defaultResult,omitempty"`

	HeartbeatTimeout *int64 `json:"heartbeatTimeout,omitempty"`

	LifecycleHookName *string `json:"lifecycleHookName,omitempty"`

	LifecycleTransition *string `json:"lifecycleTransition,omitempty"`

	NotificationMetadata *string `json:"notificationMetadata,omitempty"`

	NotificationTargetARN *string `json:"notificationTargetARN,omitempty"`

	RoleARN *string `json:"roleARN,omitempty"`
}

// +kubebuilder:skipversion
type LoadBalancerState struct {
	LoadBalancerName *string `json:"loadBalancerName,omitempty"`

	State *string `json:"state,omitempty"`
}

// +kubebuilder:skipversion
type LoadBalancerTargetGroupState struct {
	LoadBalancerTargetGroupARN *string `json:"loadBalancerTargetGroupARN,omitempty"`

	State *string `json:"state,omitempty"`
}

// +kubebuilder:skipversion
type MetricCollectionType struct {
	Metric *string `json:"metric,omitempty"`
}

// +kubebuilder:skipversion
type MetricGranularityType struct {
	Granularity *string `json:"granularity,omitempty"`
}

// +kubebuilder:skipversion
type MixedInstancesPolicy struct {
	// Describes an instances distribution for an Auto Scaling group with a MixedInstancesPolicy.
	//
	// The instances distribution specifies the distribution of On-Demand Instances
	// and Spot Instances, the maximum price to pay for Spot Instances, and how
	// the Auto Scaling group allocates instance types to fulfill On-Demand and
	// Spot capacities.
	//
	// When you update SpotAllocationStrategy, SpotInstancePools, or SpotMaxPrice,
	// this update action does not deploy any changes across the running Amazon
	// EC2 instances in the group. Your existing Spot Instances continue to run
	// as long as the maximum price for those instances is higher than the current
	// Spot price. When scale out occurs, Amazon EC2 Auto Scaling launches instances
	// based on the new settings. When scale in occurs, Amazon EC2 Auto Scaling
	// terminates instances according to the group's termination policies.
	InstancesDistribution *InstancesDistribution `json:"instancesDistribution,omitempty"`
	// Describes a launch template and overrides.
	//
	// You specify these parameters as part of a mixed instances policy.
	//
	// When you update the launch template or overrides, existing Amazon EC2 instances
	// continue to run. When scale out occurs, Amazon EC2 Auto Scaling launches
	// instances to match the new settings. When scale in occurs, Amazon EC2 Auto
	// Scaling terminates instances according to the group's termination policies.
	LaunchTemplate *LaunchTemplate `json:"launchTemplate,omitempty"`
}

// +kubebuilder:skipversion
type NotificationConfiguration struct {
	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	NotificationType *string `json:"notificationType,omitempty"`

	TopicARN *string `json:"topicARN,omitempty"`
}

// +kubebuilder:skipversion
type PredefinedMetricSpecification struct {
	ResourceLabel *string `json:"resourceLabel,omitempty"`
}

// +kubebuilder:skipversion
type ProcessType struct {
	ProcessName *string `json:"processName,omitempty"`
}

// +kubebuilder:skipversion
type ScalingPolicy struct {
	AdjustmentType *string `json:"adjustmentType,omitempty"`

	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	Cooldown *int64 `json:"cooldown,omitempty"`

	MetricAggregationType *string `json:"metricAggregationType,omitempty"`

	PolicyARN *string `json:"policyARN,omitempty"`

	PolicyName *string `json:"policyName,omitempty"`

	PolicyType *string `json:"policyType,omitempty"`
}

// +kubebuilder:skipversion
type ScheduledUpdateGroupAction struct {
	AutoScalingGroupName *string `json:"autoScalingGroupName,omitempty"`

	DesiredCapacity *int64 `json:"desiredCapacity,omitempty"`

	EndTime *metav1.Time `json:"endTime,omitempty"`

	MaxSize *int64 `json:"maxSize,omitempty"`

	MinSize *int64 `json:"minSize,omitempty"`

	Recurrence *string `json:"recurrence,omitempty"`

	ScheduledActionARN *string `json:"scheduledActionARN,omitempty"`

	ScheduledActionName *string `json:"scheduledActionName,omitempty"`

	StartTime *metav1.Time `json:"startTime,omitempty"`

	Time *metav1.Time `json:"time,omitempty"`
}

// +kubebuilder:skipversion
type ScheduledUpdateGroupActionRequest struct {
	DesiredCapacity *int64 `json:"desiredCapacity,omitempty"`

	EndTime *metav1.Time `json:"endTime,omitempty"`

	MaxSize *int64 `json:"maxSize,omitempty"`

	MinSize *int64 `json:"minSize,omitempty"`

	Recurrence *string `json:"recurrence,omitempty"`

	ScheduledActionName *string `json:"scheduledActionName,omitempty"`

	StartTime *metav1.Time `json:"startTime,omitempty"`
}

// +kubebuilder:skipversion
type SuspendedProcess struct {
	ProcessName *string `json:"processName,omitempty"`

	SuspensionReason *string `json:"suspensionReason,omitempty"`
}

// +kubebuilder:skipversion
type Tag struct {
	Key *string `json:"key,omitempty"`

	PropagateAtLaunch *bool `json:"propagateAtLaunch,omitempty"`

	ResourceID *string `json:"resourceID,omitempty"`

	ResourceType *string `json:"resourceType,omitempty"`

	Value *string `json:"value,omitempty"`
}

// +kubebuilder:skipversion
type TagDescription struct {
	Key *string `json:"key,omitempty"`

	PropagateAtLaunch *bool `json:"propagateAtLaunch,omitempty"`

	ResourceID *string `json:"resourceID,omitempty"`

	ResourceType *string `json:"resourceType,omitempty"`

	Value *string `json:"value,omitempty"`
}
